version: "3.8"

services:
  db:
    build:
      context: ./db
    container_name: sql_server
    environment:
      SA_PASSWORD: ${SQL_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - backend

  api:
    build:
      context: ./api
    container_name: dotnet_api
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - backend

  ui:
    build: ./ui
    ports:
      - "3000:4200"
    depends_on:
      - api
    networks:
      - backend

volumes:
  sqlserverdata:

networks:
  backend:
    driver: bridge
